# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(902, 520))
        MainWindow.setMaximumSize(QtCore.QSize(902, 1000))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SliderChannelA = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderChannelA.sizePolicy().hasHeightForWidth())
        self.SliderChannelA.setSizePolicy(sizePolicy)
        self.SliderChannelA.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderChannelA.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderChannelA.setMaximum(4095)
        self.SliderChannelA.setProperty("value", 0)
        self.SliderChannelA.setSliderPosition(0)
        self.SliderChannelA.setTracking(True)
        self.SliderChannelA.setOrientation(QtCore.Qt.Vertical)
        self.SliderChannelA.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderChannelA.setTickInterval(256)
        self.SliderChannelA.setObjectName("SliderChannelA")
        self.verticalLayout_3.addWidget(self.SliderChannelA, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxChannelA = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxChannelA.sizePolicy().hasHeightForWidth())
        self.SpinBoxChannelA.setSizePolicy(sizePolicy)
        self.SpinBoxChannelA.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxChannelA.setPrefix("")
        self.SpinBoxChannelA.setDecimals(4)
        self.SpinBoxChannelA.setMaximum(100.0)
        self.SpinBoxChannelA.setSingleStep(1.0)
        self.SpinBoxChannelA.setObjectName("SpinBoxChannelA")
        self.verticalLayout_3.addWidget(self.SpinBoxChannelA, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.VrefChannelA = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefChannelA.sizePolicy().hasHeightForWidth())
        self.VrefChannelA.setSizePolicy(sizePolicy)
        self.VrefChannelA.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefChannelA.setObjectName("VrefChannelA")
        self.VrefChannelA.addItem("")
        self.VrefChannelA.addItem("")
        self.VrefChannelA.addItem("")
        self.horizontalLayout_2.addWidget(self.VrefChannelA)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignHCenter)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SliderChannelB = QtWidgets.QSlider(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderChannelB.sizePolicy().hasHeightForWidth())
        self.SliderChannelB.setSizePolicy(sizePolicy)
        self.SliderChannelB.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderChannelB.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderChannelB.setMaximum(4095)
        self.SliderChannelB.setProperty("value", 0)
        self.SliderChannelB.setSliderPosition(0)
        self.SliderChannelB.setTracking(True)
        self.SliderChannelB.setOrientation(QtCore.Qt.Vertical)
        self.SliderChannelB.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderChannelB.setTickInterval(256)
        self.SliderChannelB.setObjectName("SliderChannelB")
        self.verticalLayout_4.addWidget(self.SliderChannelB, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxChannelB = QtWidgets.QDoubleSpinBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxChannelB.sizePolicy().hasHeightForWidth())
        self.SpinBoxChannelB.setSizePolicy(sizePolicy)
        self.SpinBoxChannelB.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxChannelB.setPrefix("")
        self.SpinBoxChannelB.setDecimals(4)
        self.SpinBoxChannelB.setMaximum(100.0)
        self.SpinBoxChannelB.setSingleStep(1.0)
        self.SpinBoxChannelB.setObjectName("SpinBoxChannelB")
        self.verticalLayout_4.addWidget(self.SpinBoxChannelB, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.VrefChannelB = QtWidgets.QComboBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefChannelB.sizePolicy().hasHeightForWidth())
        self.VrefChannelB.setSizePolicy(sizePolicy)
        self.VrefChannelB.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefChannelB.setObjectName("VrefChannelB")
        self.VrefChannelB.addItem("")
        self.VrefChannelB.addItem("")
        self.VrefChannelB.addItem("")
        self.horizontalLayout_3.addWidget(self.VrefChannelB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox1, 0, QtCore.Qt.AlignHCenter)
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SliderChannelC = QtWidgets.QSlider(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderChannelC.sizePolicy().hasHeightForWidth())
        self.SliderChannelC.setSizePolicy(sizePolicy)
        self.SliderChannelC.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderChannelC.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderChannelC.setMaximum(4095)
        self.SliderChannelC.setProperty("value", 0)
        self.SliderChannelC.setSliderPosition(0)
        self.SliderChannelC.setTracking(True)
        self.SliderChannelC.setOrientation(QtCore.Qt.Vertical)
        self.SliderChannelC.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderChannelC.setTickInterval(256)
        self.SliderChannelC.setObjectName("SliderChannelC")
        self.verticalLayout.addWidget(self.SliderChannelC, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxChannelC = QtWidgets.QDoubleSpinBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxChannelC.sizePolicy().hasHeightForWidth())
        self.SpinBoxChannelC.setSizePolicy(sizePolicy)
        self.SpinBoxChannelC.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxChannelC.setPrefix("")
        self.SpinBoxChannelC.setDecimals(4)
        self.SpinBoxChannelC.setMaximum(100.0)
        self.SpinBoxChannelC.setSingleStep(1.0)
        self.SpinBoxChannelC.setObjectName("SpinBoxChannelC")
        self.verticalLayout.addWidget(self.SpinBoxChannelC, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.VrefChannelC = QtWidgets.QComboBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefChannelC.sizePolicy().hasHeightForWidth())
        self.VrefChannelC.setSizePolicy(sizePolicy)
        self.VrefChannelC.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefChannelC.setObjectName("VrefChannelC")
        self.VrefChannelC.addItem("")
        self.VrefChannelC.addItem("")
        self.VrefChannelC.addItem("")
        self.horizontalLayout_4.addWidget(self.VrefChannelC)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.groupBox2, 0, QtCore.Qt.AlignHCenter)
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox3.setObjectName("groupBox3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SliderChannelD = QtWidgets.QSlider(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderChannelD.sizePolicy().hasHeightForWidth())
        self.SliderChannelD.setSizePolicy(sizePolicy)
        self.SliderChannelD.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderChannelD.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderChannelD.setMaximum(4095)
        self.SliderChannelD.setProperty("value", 0)
        self.SliderChannelD.setSliderPosition(0)
        self.SliderChannelD.setTracking(True)
        self.SliderChannelD.setOrientation(QtCore.Qt.Vertical)
        self.SliderChannelD.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderChannelD.setTickInterval(256)
        self.SliderChannelD.setObjectName("SliderChannelD")
        self.verticalLayout_2.addWidget(self.SliderChannelD, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxChannelD = QtWidgets.QDoubleSpinBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxChannelD.sizePolicy().hasHeightForWidth())
        self.SpinBoxChannelD.setSizePolicy(sizePolicy)
        self.SpinBoxChannelD.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxChannelD.setPrefix("")
        self.SpinBoxChannelD.setDecimals(4)
        self.SpinBoxChannelD.setMaximum(100.0)
        self.SpinBoxChannelD.setSingleStep(1.0)
        self.SpinBoxChannelD.setObjectName("SpinBoxChannelD")
        self.verticalLayout_2.addWidget(self.SpinBoxChannelD, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.VrefChannelD = QtWidgets.QComboBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefChannelD.sizePolicy().hasHeightForWidth())
        self.VrefChannelD.setSizePolicy(sizePolicy)
        self.VrefChannelD.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefChannelD.setObjectName("VrefChannelD")
        self.VrefChannelD.addItem("")
        self.VrefChannelD.addItem("")
        self.VrefChannelD.addItem("")
        self.horizontalLayout_5.addWidget(self.VrefChannelD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.groupBox3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10, 0, QtCore.Qt.AlignRight)
        self.SpinBoxAddress = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxAddress.sizePolicy().hasHeightForWidth())
        self.SpinBoxAddress.setSizePolicy(sizePolicy)
        self.SpinBoxAddress.setMinimumSize(QtCore.QSize(90, 27))
        self.SpinBoxAddress.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferUppercase)
        self.SpinBoxAddress.setMinimum(96)
        self.SpinBoxAddress.setMaximum(103)
        self.SpinBoxAddress.setProperty("value", 96)
        self.SpinBoxAddress.setDisplayIntegerBase(16)
        self.SpinBoxAddress.setObjectName("SpinBoxAddress")
        self.horizontalLayout_7.addWidget(self.SpinBoxAddress)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.ComboBoxBus = ComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBoxBus.sizePolicy().hasHeightForWidth())
        self.ComboBoxBus.setSizePolicy(sizePolicy)
        self.ComboBoxBus.setMinimumSize(QtCore.QSize(120, 0))
        self.ComboBoxBus.setEditable(False)
        self.ComboBoxBus.setCurrentText("")
        self.ComboBoxBus.setObjectName("ComboBoxBus")
        self.horizontalLayout_8.addWidget(self.ComboBoxBus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9, 0, QtCore.Qt.AlignRight)
        self.SpinBoxVdd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxVdd.sizePolicy().hasHeightForWidth())
        self.SpinBoxVdd.setSizePolicy(sizePolicy)
        self.SpinBoxVdd.setMinimumSize(QtCore.QSize(90, 27))
        self.SpinBoxVdd.setDecimals(3)
        self.SpinBoxVdd.setMinimum(2.7)
        self.SpinBoxVdd.setMaximum(5.5)
        self.SpinBoxVdd.setObjectName("SpinBoxVdd")
        self.horizontalLayout_6.addWidget(self.SpinBoxVdd)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.CheckBoxUpdate = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBoxUpdate.sizePolicy().hasHeightForWidth())
        self.CheckBoxUpdate.setSizePolicy(sizePolicy)
        self.CheckBoxUpdate.setMinimumSize(QtCore.QSize(170, 0))
        self.CheckBoxUpdate.setObjectName("CheckBoxUpdate")
        self.horizontalLayout_9.addWidget(self.CheckBoxUpdate)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 3, 1, 1)
        self.PushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonLoad.sizePolicy().hasHeightForWidth())
        self.PushButtonLoad.setSizePolicy(sizePolicy)
        self.PushButtonLoad.setMinimumSize(QtCore.QSize(160, 0))
        self.PushButtonLoad.setObjectName("PushButtonLoad")
        self.gridLayout.addWidget(self.PushButtonLoad, 1, 6, 1, 1)
        self.PushButtonWrite = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonWrite.sizePolicy().hasHeightForWidth())
        self.PushButtonWrite.setSizePolicy(sizePolicy)
        self.PushButtonWrite.setMinimumSize(QtCore.QSize(120, 0))
        self.PushButtonWrite.setObjectName("PushButtonWrite")
        self.gridLayout.addWidget(self.PushButtonWrite, 0, 5, 1, 1)
        self.PushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSave.sizePolicy().hasHeightForWidth())
        self.PushButtonSave.setSizePolicy(sizePolicy)
        self.PushButtonSave.setMinimumSize(QtCore.QSize(160, 0))
        self.PushButtonSave.setObjectName("PushButtonSave")
        self.gridLayout.addWidget(self.PushButtonSave, 0, 6, 1, 1)
        self.PushButtonRead = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonRead.sizePolicy().hasHeightForWidth())
        self.PushButtonRead.setSizePolicy(sizePolicy)
        self.PushButtonRead.setMinimumSize(QtCore.QSize(120, 0))
        self.PushButtonRead.setObjectName("PushButtonRead")
        self.gridLayout.addWidget(self.PushButtonRead, 1, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 7, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.VrefChannelA)
        self.label_2.setBuddy(self.VrefChannelB)
        self.label_3.setBuddy(self.VrefChannelC)
        self.label_4.setBuddy(self.VrefChannelD)
        self.label_10.setBuddy(self.SpinBoxAddress)
        self.label_9.setBuddy(self.SpinBoxVdd)

        self.retranslateUi(MainWindow)
        self.VrefChannelD.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCP4728 GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "Channel A"))
        self.SpinBoxChannelA.setSuffix(_translate("MainWindow", " V"))
        self.label.setText(_translate("MainWindow", " Vref"))
        self.VrefChannelA.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefChannelA.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefChannelA.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.groupBox1.setTitle(_translate("MainWindow", "Channel B"))
        self.SpinBoxChannelB.setSuffix(_translate("MainWindow", " V"))
        self.label_2.setText(_translate("MainWindow", " Vref"))
        self.VrefChannelB.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefChannelB.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefChannelB.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.groupBox2.setTitle(_translate("MainWindow", "Channel C"))
        self.SpinBoxChannelC.setSuffix(_translate("MainWindow", " V"))
        self.label_3.setText(_translate("MainWindow", " Vref"))
        self.VrefChannelC.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefChannelC.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefChannelC.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.groupBox3.setTitle(_translate("MainWindow", "Channel D"))
        self.SpinBoxChannelD.setSuffix(_translate("MainWindow", " V"))
        self.label_4.setText(_translate("MainWindow", " Vref"))
        self.VrefChannelD.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefChannelD.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefChannelD.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.label_10.setText(_translate("MainWindow", "i2c address"))
        self.SpinBoxAddress.setPrefix(_translate("MainWindow", "0x"))
        self.label_5.setText(_translate("MainWindow", "i2c bus"))
        self.label_9.setText(_translate("MainWindow", "Vdd voltage"))
        self.SpinBoxVdd.setSuffix(_translate("MainWindow", " V"))
        self.CheckBoxUpdate.setText(_translate("MainWindow", "Continuous update"))
        self.PushButtonLoad.setText(_translate("MainWindow", "Load from EEPROM"))
        self.PushButtonWrite.setText(_translate("MainWindow", "Write values"))
        self.PushButtonSave.setText(_translate("MainWindow", "Save to EEPROM"))
        self.PushButtonRead.setText(_translate("MainWindow", "Read values"))
from ComboBox import ComboBox
