# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 639)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(902, 520))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 1000))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(428, 0))
        self.frame.setMaximumSize(QtCore.QSize(512, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.centerFreqSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.centerFreqSpinBox.setMaximum(1000.0)
        self.centerFreqSpinBox.setProperty("value", 500.0)
        self.centerFreqSpinBox.setObjectName("centerFreqSpinBox")
        self.gridLayout_2.addWidget(self.centerFreqSpinBox, 4, 2, 1, 1)
        self.rippleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.rippleSpinBox.setProperty("value", 3.0)
        self.rippleSpinBox.setObjectName("rippleSpinBox")
        self.gridLayout_2.addWidget(self.rippleSpinBox, 0, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_2.addWidget(self.radioButton_3, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 1, 1, 1)
        self.fbwSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.fbwSpinBox.setMaximum(100.0)
        self.fbwSpinBox.setProperty("value", 50.0)
        self.fbwSpinBox.setObjectName("fbwSpinBox")
        self.gridLayout_2.addWidget(self.fbwSpinBox, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 0, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.frame)
        self.plotWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.horizontalLayout.addWidget(self.plotWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10, 0, QtCore.Qt.AlignRight)
        self.SpinBoxAddress = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxAddress.sizePolicy().hasHeightForWidth())
        self.SpinBoxAddress.setSizePolicy(sizePolicy)
        self.SpinBoxAddress.setMinimumSize(QtCore.QSize(115, 28))
        self.SpinBoxAddress.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferUppercase)
        self.SpinBoxAddress.setMinimum(96)
        self.SpinBoxAddress.setMaximum(103)
        self.SpinBoxAddress.setProperty("value", 96)
        self.SpinBoxAddress.setDisplayIntegerBase(16)
        self.SpinBoxAddress.setObjectName("SpinBoxAddress")
        self.horizontalLayout_7.addWidget(self.SpinBoxAddress)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.ComboBoxBus = ComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBoxBus.sizePolicy().hasHeightForWidth())
        self.ComboBoxBus.setSizePolicy(sizePolicy)
        self.ComboBoxBus.setMinimumSize(QtCore.QSize(120, 0))
        self.ComboBoxBus.setEditable(False)
        self.ComboBoxBus.setCurrentText("")
        self.ComboBoxBus.setObjectName("ComboBoxBus")
        self.horizontalLayout_8.addWidget(self.ComboBoxBus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9, 0, QtCore.Qt.AlignRight)
        self.SpinBoxVdd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxVdd.sizePolicy().hasHeightForWidth())
        self.SpinBoxVdd.setSizePolicy(sizePolicy)
        self.SpinBoxVdd.setMinimumSize(QtCore.QSize(125, 28))
        self.SpinBoxVdd.setDecimals(3)
        self.SpinBoxVdd.setMinimum(2.7)
        self.SpinBoxVdd.setMaximum(5.5)
        self.SpinBoxVdd.setObjectName("SpinBoxVdd")
        self.horizontalLayout_6.addWidget(self.SpinBoxVdd)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.CheckBoxUpdate = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBoxUpdate.sizePolicy().hasHeightForWidth())
        self.CheckBoxUpdate.setSizePolicy(sizePolicy)
        self.CheckBoxUpdate.setMinimumSize(QtCore.QSize(170, 0))
        self.CheckBoxUpdate.setObjectName("CheckBoxUpdate")
        self.horizontalLayout_9.addWidget(self.CheckBoxUpdate)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 3, 1, 1)
        self.PushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonLoad.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonLoad.sizePolicy().hasHeightForWidth())
        self.PushButtonLoad.setSizePolicy(sizePolicy)
        self.PushButtonLoad.setMinimumSize(QtCore.QSize(160, 0))
        self.PushButtonLoad.setObjectName("PushButtonLoad")
        self.gridLayout.addWidget(self.PushButtonLoad, 1, 6, 1, 1)
        self.PushButtonWrite = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonWrite.sizePolicy().hasHeightForWidth())
        self.PushButtonWrite.setSizePolicy(sizePolicy)
        self.PushButtonWrite.setMinimumSize(QtCore.QSize(120, 0))
        self.PushButtonWrite.setObjectName("PushButtonWrite")
        self.gridLayout.addWidget(self.PushButtonWrite, 0, 5, 1, 1)
        self.PushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSave.sizePolicy().hasHeightForWidth())
        self.PushButtonSave.setSizePolicy(sizePolicy)
        self.PushButtonSave.setMinimumSize(QtCore.QSize(160, 0))
        self.PushButtonSave.setObjectName("PushButtonSave")
        self.gridLayout.addWidget(self.PushButtonSave, 0, 6, 1, 1)
        self.PushButtonRead = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonRead.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonRead.sizePolicy().hasHeightForWidth())
        self.PushButtonRead.setSizePolicy(sizePolicy)
        self.PushButtonRead.setMinimumSize(QtCore.QSize(120, 0))
        self.PushButtonRead.setFlat(False)
        self.PushButtonRead.setObjectName("PushButtonRead")
        self.gridLayout.addWidget(self.PushButtonRead, 1, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 7, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_10.setBuddy(self.SpinBoxAddress)
        self.label_9.setBuddy(self.SpinBoxVdd)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tunable Filter GUI"))
        MainWindow.setProperty("LICENSE", _translate("MainWindow", "MCP4728 PyQt5 GUI\n"
"Copyright (C) 2019 Luca Anastasio\n"
"<anastasio.lu@gmail.com>\n"
"\n"
"This program is free software: you can redistribute it and/or modify\n"
"it under the terms of the GNU General Public License as published by\n"
"the Free Software Foundation, either version 3 of the License, or\n"
"(at your option) any later version.\n"
"\n"
"This program is distributed in the hope that it will be useful,\n"
"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"GNU General Public License for more details.\n"
"\n"
"You should have received a copy of the GNU General Public License\n"
"along with this program.  If not, see <http://www.gnu.org/licenses/>."))
        self.centerFreqSpinBox.setSuffix(_translate("MainWindow", " MHz"))
        self.rippleSpinBox.setSuffix(_translate("MainWindow", " dB"))
        self.radioButton_3.setText(_translate("MainWindow", "Center and Bandwidth"))
        self.radioButton_2.setText(_translate("MainWindow", "Butterworth"))
        self.fbwSpinBox.setSuffix(_translate("MainWindow", " %"))
        self.radioButton.setText(_translate("MainWindow", "Chebyshev"))
        self.radioButton_4.setText(_translate("MainWindow", "Cutoff frequencies"))
        self.label_2.setText(_translate("MainWindow", "Fractional BW"))
        self.label_3.setText(_translate("MainWindow", "Center frequency"))
        self.label.setText(_translate("MainWindow", "Ripple"))
        self.label_10.setText(_translate("MainWindow", "i2c address"))
        self.SpinBoxAddress.setPrefix(_translate("MainWindow", "0x"))
        self.label_5.setText(_translate("MainWindow", "i2c bus"))
        self.label_9.setText(_translate("MainWindow", "Vdd voltage"))
        self.SpinBoxVdd.setSuffix(_translate("MainWindow", " V"))
        self.CheckBoxUpdate.setText(_translate("MainWindow", "Continuous update"))
        self.PushButtonLoad.setText(_translate("MainWindow", "Load from EEPROM"))
        self.PushButtonWrite.setText(_translate("MainWindow", "Write values"))
        self.PushButtonSave.setText(_translate("MainWindow", "Save to EEPROM"))
        self.PushButtonRead.setText(_translate("MainWindow", "Read values"))
from .ComboBox import ComboBox
from pyqtgraph import PlotWidget
