# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(902, 520))
        MainWindow.setMaximumSize(QtCore.QSize(902, 1000))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("border-color: black")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SliderA = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderA.sizePolicy().hasHeightForWidth())
        self.SliderA.setSizePolicy(sizePolicy)
        self.SliderA.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderA.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderA.setMaximum(4095)
        self.SliderA.setPageStep(12)
        self.SliderA.setProperty("value", 0)
        self.SliderA.setSliderPosition(0)
        self.SliderA.setTracking(True)
        self.SliderA.setOrientation(QtCore.Qt.Vertical)
        self.SliderA.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderA.setTickInterval(256)
        self.SliderA.setObjectName("SliderA")
        self.verticalLayout_3.addWidget(self.SliderA, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxA = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxA.sizePolicy().hasHeightForWidth())
        self.SpinBoxA.setSizePolicy(sizePolicy)
        self.SpinBoxA.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxA.setPrefix("")
        self.SpinBoxA.setDecimals(4)
        self.SpinBoxA.setMaximum(2.0475)
        self.SpinBoxA.setSingleStep(0.0005)
        self.SpinBoxA.setObjectName("SpinBoxA")
        self.verticalLayout_3.addWidget(self.SpinBoxA, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.VrefA = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefA.sizePolicy().hasHeightForWidth())
        self.VrefA.setSizePolicy(sizePolicy)
        self.VrefA.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefA.setObjectName("VrefA")
        self.VrefA.addItem("")
        self.VrefA.addItem("")
        self.VrefA.addItem("")
        self.horizontalLayout_2.addWidget(self.VrefA)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignHCenter)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setStyleSheet("border-color: black")
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SliderB = QtWidgets.QSlider(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderB.sizePolicy().hasHeightForWidth())
        self.SliderB.setSizePolicy(sizePolicy)
        self.SliderB.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderB.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderB.setMaximum(4095)
        self.SliderB.setPageStep(12)
        self.SliderB.setProperty("value", 0)
        self.SliderB.setSliderPosition(0)
        self.SliderB.setTracking(True)
        self.SliderB.setOrientation(QtCore.Qt.Vertical)
        self.SliderB.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderB.setTickInterval(256)
        self.SliderB.setObjectName("SliderB")
        self.verticalLayout_4.addWidget(self.SliderB, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxB = QtWidgets.QDoubleSpinBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxB.sizePolicy().hasHeightForWidth())
        self.SpinBoxB.setSizePolicy(sizePolicy)
        self.SpinBoxB.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxB.setPrefix("")
        self.SpinBoxB.setDecimals(4)
        self.SpinBoxB.setMaximum(2.0475)
        self.SpinBoxB.setSingleStep(0.0005)
        self.SpinBoxB.setObjectName("SpinBoxB")
        self.verticalLayout_4.addWidget(self.SpinBoxB, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.VrefB = QtWidgets.QComboBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefB.sizePolicy().hasHeightForWidth())
        self.VrefB.setSizePolicy(sizePolicy)
        self.VrefB.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefB.setObjectName("VrefB")
        self.VrefB.addItem("")
        self.VrefB.addItem("")
        self.VrefB.addItem("")
        self.horizontalLayout_3.addWidget(self.VrefB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox1, 0, QtCore.Qt.AlignHCenter)
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setStyleSheet("border-color: black")
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SliderC = QtWidgets.QSlider(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderC.sizePolicy().hasHeightForWidth())
        self.SliderC.setSizePolicy(sizePolicy)
        self.SliderC.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderC.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderC.setMaximum(4095)
        self.SliderC.setPageStep(12)
        self.SliderC.setProperty("value", 0)
        self.SliderC.setSliderPosition(0)
        self.SliderC.setTracking(True)
        self.SliderC.setOrientation(QtCore.Qt.Vertical)
        self.SliderC.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderC.setTickInterval(256)
        self.SliderC.setObjectName("SliderC")
        self.verticalLayout.addWidget(self.SliderC, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxC = QtWidgets.QDoubleSpinBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxC.sizePolicy().hasHeightForWidth())
        self.SpinBoxC.setSizePolicy(sizePolicy)
        self.SpinBoxC.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxC.setPrefix("")
        self.SpinBoxC.setDecimals(4)
        self.SpinBoxC.setMaximum(2.0475)
        self.SpinBoxC.setSingleStep(0.0005)
        self.SpinBoxC.setObjectName("SpinBoxC")
        self.verticalLayout.addWidget(self.SpinBoxC, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.VrefC = QtWidgets.QComboBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefC.sizePolicy().hasHeightForWidth())
        self.VrefC.setSizePolicy(sizePolicy)
        self.VrefC.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefC.setObjectName("VrefC")
        self.VrefC.addItem("")
        self.VrefC.addItem("")
        self.VrefC.addItem("")
        self.horizontalLayout_4.addWidget(self.VrefC)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.groupBox2, 0, QtCore.Qt.AlignHCenter)
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setStyleSheet("border-color: black")
        self.groupBox3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox3.setObjectName("groupBox3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SliderD = QtWidgets.QSlider(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderD.sizePolicy().hasHeightForWidth())
        self.SliderD.setSizePolicy(sizePolicy)
        self.SliderD.setMinimumSize(QtCore.QSize(0, 256))
        self.SliderD.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderD.setMaximum(4095)
        self.SliderD.setPageStep(12)
        self.SliderD.setProperty("value", 0)
        self.SliderD.setSliderPosition(0)
        self.SliderD.setTracking(True)
        self.SliderD.setOrientation(QtCore.Qt.Vertical)
        self.SliderD.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderD.setTickInterval(256)
        self.SliderD.setObjectName("SliderD")
        self.verticalLayout_2.addWidget(self.SliderD, 0, QtCore.Qt.AlignHCenter)
        self.SpinBoxD = QtWidgets.QDoubleSpinBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxD.sizePolicy().hasHeightForWidth())
        self.SpinBoxD.setSizePolicy(sizePolicy)
        self.SpinBoxD.setMinimumSize(QtCore.QSize(110, 0))
        self.SpinBoxD.setPrefix("")
        self.SpinBoxD.setDecimals(4)
        self.SpinBoxD.setMaximum(2.0475)
        self.SpinBoxD.setSingleStep(0.0005)
        self.SpinBoxD.setObjectName("SpinBoxD")
        self.verticalLayout_2.addWidget(self.SpinBoxD, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.VrefD = QtWidgets.QComboBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VrefD.sizePolicy().hasHeightForWidth())
        self.VrefD.setSizePolicy(sizePolicy)
        self.VrefD.setMinimumSize(QtCore.QSize(140, 0))
        self.VrefD.setObjectName("VrefD")
        self.VrefD.addItem("")
        self.VrefD.addItem("")
        self.VrefD.addItem("")
        self.horizontalLayout_5.addWidget(self.VrefD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.groupBox3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10, 0, QtCore.Qt.AlignRight)
        self.SpinBoxAddress = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxAddress.sizePolicy().hasHeightForWidth())
        self.SpinBoxAddress.setSizePolicy(sizePolicy)
        self.SpinBoxAddress.setMinimumSize(QtCore.QSize(90, 27))
        self.SpinBoxAddress.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferUppercase)
        self.SpinBoxAddress.setMinimum(96)
        self.SpinBoxAddress.setMaximum(103)
        self.SpinBoxAddress.setProperty("value", 96)
        self.SpinBoxAddress.setDisplayIntegerBase(16)
        self.SpinBoxAddress.setObjectName("SpinBoxAddress")
        self.horizontalLayout_7.addWidget(self.SpinBoxAddress)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.ComboBoxBus = ComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBoxBus.sizePolicy().hasHeightForWidth())
        self.ComboBoxBus.setSizePolicy(sizePolicy)
        self.ComboBoxBus.setMinimumSize(QtCore.QSize(120, 0))
        self.ComboBoxBus.setEditable(False)
        self.ComboBoxBus.setCurrentText("")
        self.ComboBoxBus.setObjectName("ComboBoxBus")
        self.horizontalLayout_8.addWidget(self.ComboBoxBus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9, 0, QtCore.Qt.AlignRight)
        self.SpinBoxVdd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBoxVdd.sizePolicy().hasHeightForWidth())
        self.SpinBoxVdd.setSizePolicy(sizePolicy)
        self.SpinBoxVdd.setMinimumSize(QtCore.QSize(90, 27))
        self.SpinBoxVdd.setDecimals(3)
        self.SpinBoxVdd.setMinimum(2.7)
        self.SpinBoxVdd.setMaximum(5.5)
        self.SpinBoxVdd.setObjectName("SpinBoxVdd")
        self.horizontalLayout_6.addWidget(self.SpinBoxVdd)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.CheckBoxUpdate = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBoxUpdate.sizePolicy().hasHeightForWidth())
        self.CheckBoxUpdate.setSizePolicy(sizePolicy)
        self.CheckBoxUpdate.setMinimumSize(QtCore.QSize(170, 0))
        self.CheckBoxUpdate.setObjectName("CheckBoxUpdate")
        self.horizontalLayout_9.addWidget(self.CheckBoxUpdate)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 3, 1, 1)
        self.PushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonLoad.sizePolicy().hasHeightForWidth())
        self.PushButtonLoad.setSizePolicy(sizePolicy)
        self.PushButtonLoad.setMinimumSize(QtCore.QSize(160, 0))
        self.PushButtonLoad.setObjectName("PushButtonLoad")
        self.gridLayout.addWidget(self.PushButtonLoad, 1, 6, 1, 1)
        self.PushButtonWrite = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonWrite.sizePolicy().hasHeightForWidth())
        self.PushButtonWrite.setSizePolicy(sizePolicy)
        self.PushButtonWrite.setMinimumSize(QtCore.QSize(120, 0))
        self.PushButtonWrite.setObjectName("PushButtonWrite")
        self.gridLayout.addWidget(self.PushButtonWrite, 0, 5, 1, 1)
        self.PushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonSave.sizePolicy().hasHeightForWidth())
        self.PushButtonSave.setSizePolicy(sizePolicy)
        self.PushButtonSave.setMinimumSize(QtCore.QSize(160, 0))
        self.PushButtonSave.setObjectName("PushButtonSave")
        self.gridLayout.addWidget(self.PushButtonSave, 0, 6, 1, 1)
        self.PushButtonRead = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButtonRead.sizePolicy().hasHeightForWidth())
        self.PushButtonRead.setSizePolicy(sizePolicy)
        self.PushButtonRead.setMinimumSize(QtCore.QSize(120, 0))
        self.PushButtonRead.setObjectName("PushButtonRead")
        self.gridLayout.addWidget(self.PushButtonRead, 1, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 7, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.VrefA)
        self.label_2.setBuddy(self.VrefB)
        self.label_3.setBuddy(self.VrefC)
        self.label_4.setBuddy(self.VrefD)
        self.label_10.setBuddy(self.SpinBoxAddress)
        self.label_9.setBuddy(self.SpinBoxVdd)

        self.retranslateUi(MainWindow)
        self.VrefD.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCP4728 GUI"))
        MainWindow.setProperty("LICENSE", _translate("MainWindow", "MCP4728 PyQt5 GUI\n"
"Copyright (C) 2019 Luca Anastasio\n"
"<anastasio.lu@gmail.com>\n"
"\n"
"This program is free software: you can redistribute it and/or modify\n"
"it under the terms of the GNU General Public License as published by\n"
"the Free Software Foundation, either version 3 of the License, or\n"
"(at your option) any later version.\n"
"\n"
"This program is distributed in the hope that it will be useful,\n"
"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"GNU General Public License for more details.\n"
"\n"
"You should have received a copy of the GNU General Public License\n"
"along with this program.  If not, see <http://www.gnu.org/licenses/>."))
        self.groupBox.setTitle(_translate("MainWindow", "Channel A"))
        self.SpinBoxA.setSuffix(_translate("MainWindow", " V"))
        self.label.setText(_translate("MainWindow", " Vref"))
        self.VrefA.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefA.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefA.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.groupBox1.setTitle(_translate("MainWindow", "Channel B"))
        self.SpinBoxB.setSuffix(_translate("MainWindow", " V"))
        self.label_2.setText(_translate("MainWindow", " Vref"))
        self.VrefB.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefB.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefB.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.groupBox2.setTitle(_translate("MainWindow", "Channel C"))
        self.SpinBoxC.setSuffix(_translate("MainWindow", " V"))
        self.label_3.setText(_translate("MainWindow", " Vref"))
        self.VrefC.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefC.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefC.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.groupBox3.setTitle(_translate("MainWindow", "Channel D"))
        self.SpinBoxD.setSuffix(_translate("MainWindow", " V"))
        self.label_4.setText(_translate("MainWindow", " Vref"))
        self.VrefD.setItemText(0, _translate("MainWindow", "Internal (2.048V)"))
        self.VrefD.setItemText(1, _translate("MainWindow", "Internal (4.096V)"))
        self.VrefD.setItemText(2, _translate("MainWindow", "External (Vdd)"))
        self.label_10.setText(_translate("MainWindow", "i2c address"))
        self.SpinBoxAddress.setPrefix(_translate("MainWindow", "0x"))
        self.label_5.setText(_translate("MainWindow", "i2c bus"))
        self.label_9.setText(_translate("MainWindow", "Vdd voltage"))
        self.SpinBoxVdd.setSuffix(_translate("MainWindow", " V"))
        self.CheckBoxUpdate.setText(_translate("MainWindow", "Continuous update"))
        self.PushButtonLoad.setText(_translate("MainWindow", "Load from EEPROM"))
        self.PushButtonWrite.setText(_translate("MainWindow", "Write values"))
        self.PushButtonSave.setText(_translate("MainWindow", "Save to EEPROM"))
        self.PushButtonRead.setText(_translate("MainWindow", "Read values"))

from ComboBox import ComboBox
